### ISSUE TITLE
Error while using XmlDuration models

### ISSUE THREAD

**Issue by SamuelYvon** [tefra/xsdata-pydantic#11]
```
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'xsdata.models.datatype.XmlDuration'>, see `arbitrary_types_allowed` in Config
```

WSDL elements that rely on `XMlDuration` fail to validate because this is not a natively supported type. 

Changing following: `@dataclass` to the following works: `@dataclass(config=dict(arbitrary_types_allowed=True))` 

This is the same for some `lxml` elements: 

```
RuntimeError: no validator found for <class 'xml.etree.ElementTree.QName'>, see `arbitrary_types_allowed` in Config
```

**Comment by tefra** [comment]
What pydantic version are you using @SamuelYvon ?

Pydantic doesn't have a public let's say api to register validators we do it like this
https://github.com/tefra/xsdata-pydantic/blame/master/xsdata_pydantic/compat.py#L107


Maybe something changed recently I will take a look

**Comment by SamuelYvon** [comment]
> What pydantic version are you using @SamuelYvon ?

I use latest as of writing, so `1.10.2`;


An easy fix (that you actually use in the source of the pydantic backend) is to change the
`@dataclass` to `@dataclass(config=dict(arbitrary_types_allowed=True))`. I specified `XMLDuration` here but there are many other instances of this happening (using WSDLs for onvif)

**Comment by tefra** [comment]
Ok I think I got it,

@SamuelYvon It's important to import the xsdata serializer/parser before working with the models, in order for the custom validators to be already registered.

This fails 
```python
from pydantic.dataclasses import dataclass
from xsdata.models.datatype import XmlDuration


@dataclass
class DurationRangeMatcherType:
    begin: XmlDuration

print(DurationRangeMatcherType(begin=XmlDuration("PT3S")))
```

This passes
```
from pydantic.dataclasses import dataclass
from xsdata.models.datatype import XmlDuration
from xsdata_pydantic.bindings import XmlSerializer. # import serializer to trigger the xsdata hook to register the validators

@dataclass
class DurationRangeMatcherType:
    begin: XmlDuration

print(DurationRangeMatcherType(begin=XmlDuration("PT3S")))
```

**Comment by tefra** [comment]
This needs to be added in the docs...

**Comment by SamuelYvon** [comment]
Ah! I see. Yes, it would be better in doc. Maybe beware that tools like `isort` (not restricted to) might mess up the order. Feel free to close this issue in that case

**Comment by tefra** [comment]
Thank you!
